Features/tsc merkle proofs (#1056)
* Add tsc merkle proof endpoint

see: https://tsc.bitcoinassociation.net/standards/merkle-proof-standardised-format/

* Fix pylint warnings

* Fix AttributeError in pytest causing tests to fail instead of skipping

- Error message: "'MarkDecorator' object has no attribute 'lower'"

* Add tsc_format option to Merkle.branch_and_root() which adds asterixes in place of "duplicate hashes"

- SessionManager._merkle_branch now always returns branch, root and cost
- Add unittest coverage for the "blockchain.transaction.get_tsc_merkle" endpoint
- Add MacOS-specific installation for plyvel / leveldb to fix a long-standing
issue with test_compaction failing in Azure. This required leveldb 1.22
as leveldb v 1.23 runs into issues with "Symbol not found: __ZTIN7leveldb10ComparatorE"

* Add documentation for TSC merkle proof format endpoint

- Reorganise into 4 separate unittests

* Account for all cost estimates (TSC merkle endpoint)